### ISSUE TITLE
android:layout_height="0dp" in graphics.DrawingView in the activity_main.xml file

### ISSUE THREAD

**Issue by nashau01** [ProjectSAEJE/ProjectSAEJE#1]
The layout_height in the DrawingView tag is set to "0dp" and the app runs with this value (A View with height 0 is flat and useless. Is the layout_height different than some view_height attribute?). Changing it to any nonzero value or fill_parent causes the app to crash and give the message "Unfortunately, ProjectSAEJE stopped running."

I can't imagine any UI element (View object) that should have height 0. We should figure out how to give the DrawingView object a nonzero height, and find its relation to the layout_height attribute in the DrawingView tag in the xml file or instantiate a View object without using XML and see if that works better.

**Comment by klugeh01** [comment]
when the layout_weight attribute is set for a view attribute, any width or height values that are 0 will be inflated to match the weight

**Comment by nashau01** [comment]
@overide onSizeChanged() method was missing from the DrawingView class.
